version: '3.8'
services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: productTest
      POSTGRES_USER: productUser
      POSTGRES_PASSWORD: productPassword
    ports:
      - "5555:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    container_name: micro1
    build:
      context: .
      dockerfile: dockerFile_newKafka
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productTest
      SPRING_DATA_SOURCE_USERNAME: productUser
      SPRING_DATASOURCE_PASSWORD: productPassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

  micro2:
    container_name: micro2
    build:
      context: .
      dockerfile: dockerFile_micro2
    ports:
      - "8081:8080"
    depends_on:
      - kafka


  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin


volumes:
  prometheus_data: {}
  db-data:


