version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: productTest
      POSTGRES_USER: productUser
      POSTGRES_PASSWORD: productPassword
    ports:
      - "5555:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: dockerFile_demo
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productTest
      SPRING_DATA_SOURCE_USERNAME: productUser
      SPRING_DATASOURCE_PASSWORD: productPassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db-data:


